# Generated by Django 4.2 on 2025-01-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('R', 'Romance'), ('I', 'Infantil'), ('C', 'Comedia'), ('T', 'Terror'), ('D', 'Drama'), ('A', 'Acción')], max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('release_year', models.IntegerField()),
            ],
        ),
    ]
