# Generated by Django 4.2 on 2025-01-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_synopsis_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('D', 'Drama'), ('A', 'Acción'), ('R', 'Romance'), ('T', 'Terror'), ('C', 'Comedia'), ('I', 'Infantil')], max_length=30),
        ),
    ]
